# Generated by Django 6.0.5 on 2026-06-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_retracted',
        ),
    ]
