# Generated by Django 5.2.12 on 2026-06-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_assignment_is_retracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена в кристаллах')),
                ('item_type', models.CharField(choices=[('consumable', 'Расходник'), ('decoration', 'Украшение'), ('booster', 'Бустер'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/', verbose_name='Изображение')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если покупка бессрочная', null=True, verbose_name='Срок действия (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает получения'), ('activated', 'Активировано'), ('expired', 'Истёк срок')], default='pending', max_length=16, verbose_name='Статус')),
                ('code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Код покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Сгорает до')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.studentprofile', verbose_name='Ученик')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shopitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-created_at'],
            },
        ),
    ]
