# Generated by Django 5.2.12 on 2026-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shopitem_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('decoration', 'Украшение'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип товара'),
        ),
    ]
