# Generated by Django 5.2.12 on 2026-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_shopitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.URLField(blank=True, help_text='Вставьте URL картинки из интернета', max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
