# Generated by Django 5.2.12 on 2026-06-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shopitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('decoration', 'Украшение'), ('other', 'Другое'), ('product', 'товар')], default='other', max_length=32, verbose_name='Тип товара'),
        ),
    ]
