# Generated by Django 6.0.5 on 2026-06-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_image_shopitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinvitecode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinvitecode',
            name='max_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacherinvitecode',
            name='ttl_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='teacherinvitecode',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('ttl_minutes', models.IntegerField(default=1440)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='api.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invite_codes', to='api.teacherprofile')),
            ],
        ),
    ]
