# Generated by Django 6.0.5 on 2026-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_teacherinvitecode_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает получения'), ('received', 'Получено'), ('expired', 'Истёк срок')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
