# Generated by Django 6.0.5 on 2026-06-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_subject_name_lesson'),
        ('api', '0012_teacherprofile_avatar'),
    ]

    operations = [
    ]
