# Generated by Django 6.0.5 on 2026-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20260610_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
