# Generated by Django 6.0.5 on 2026-06-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_assignment_feedback_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='feedback',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
