# Generated by Django 6.0.5 on 2026-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_group_teacher_group_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(max_length=128),
        ),
    ]
