# Generated by Django 6.0.5 on 2026-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_lesson_subject_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='weekday',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
