# Generated by Django 6.0.5 on 2026-06-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_attendance_crystals_awarded_attendance_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, help_text='Место среди учеников в группе')),
                ('completed_assignments', models.IntegerField(default=0, help_text='Количество выполненных заданий')),
                ('incomplete_assignments', models.IntegerField(default=0, help_text='Количество невыполненных заданий')),
                ('total_xp', models.IntegerField(default=0, help_text='Общий опыт')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.studentprofile')),
            ],
            options={
                'verbose_name': 'Статистика ученика',
                'verbose_name_plural': 'Статистика учеников',
            },
        ),
    ]
