# Generated by Django 5.2.12 on 2026-06-19 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_attendance_crystals_awarded_attendance_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('login', 'Вход в систему'), ('attend_lesson', 'Посетить урок'), ('submit_assignment', 'Сдать задание'), ('buy_item', 'Купить товар'), ('earn_xp', 'Заработать N XP')], max_length=32)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('crystal_reward', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.subject'),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('lessons_attended', 'Посещено уроков'), ('assignments_submitted', 'Сдано заданий'), ('total_xp', 'Накоплено XP'), ('items_bought', 'Куплено товаров')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='crystal_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='required_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Требуемый уровень'),
        ),
        migrations.CreateModel(
            name='LevelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('crystals_bonus', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.badge')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dailyquest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'quest', 'date')},
            },
        ),
    ]
