# Generated by Django 6.0.5 on 2026-06-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_studentstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAverageGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('average_grade', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_grades', to='api.studentprofile')),
            ],
            options={
                'verbose_name': 'Средняя оценка за месяц',
                'verbose_name_plural': 'Средние оценки за месяцы',
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
