# Generated by Django 6.0.5 on 2026-06-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_dailyquest_assignment_subject_badge_condition_type_and_more'),
        ('api', '0023_monthlyaveragegrade'),
    ]

    operations = [
    ]
