# Generated by Django 6.0.5 on 2026-06-24 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_default_daily_quest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment_graded', 'Задание оценено'), ('assignment_submitted', 'Задание сдано'), ('lesson_graded', 'Оценка за урок'), ('new_assignment', 'Новое задание'), ('attendance_marked', 'Отметка о посещении'), ('level_up', 'Повышение уровня'), ('badge_earned', 'Получен значок'), ('crystals_awarded', 'Начислены кристаллы')], max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Опциональная ссылка для перехода', max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
