# Generated by Django 5.2.12 on 2026-06-25 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('choice', models.CharField(choices=[('red', 'Красное'), ('black', 'Черное'), ('green', 'Зеленое')], max_length=5)),
                ('result_color', models.CharField(blank=True, choices=[('red', 'Красное'), ('black', 'Черное'), ('green', 'Зеленое')], max_length=5, null=True)),
                ('win', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_bets', to='api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
