from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import (
    RegisterView,
    LoginView,
    GroupViewSet,
    AssignmentViewSet,
    StudentAssignmentFeedView,
    TeacherAssignmentFeedView,
    ChangeCrystalsView,
    MyStudentProfileView,
    MyStudentAvatarView,
    MyTeacherProfileView,
    PublicStudentProfileView,
    PublicTeacherProfileView,
    GenerateTeacherInviteCodeView,
    ShopItemListView,
    BuyItemView,
    MyPurchasesView,
    ActivatePurchaseView,
    TeacherStudentPurchasesView,
    GroupInviteCodeView,
    StudentJoinGroupView,
    LessonViewSet,
    ScheduleView,
    TeacherStudentsView,
    StudentAssignmentsView,
    GradeAssignmentView,
    LessonAttendanceView,
    CurrentLessonView,
    StudentStatisticsView,
    GroupLeaderboardView,
    MonthlyGradesView,
    DailyQuestView,
    BadgeListView,
    MyBadgeView,
    LevelRewardListView,
    RouletteView,
)
from . import views
from api.views_admin import AdminDashboardView, AdminInviteCodeView, AdminGroupLessonsView, AdminGroupLessonDetailView
from rest_framework_simplejwt.views import TokenRefreshView
from api.views_notifications import (
    NotificationListView,
    NotificationUnreadCountView,
    NotificationMarkReadView
)


router = DefaultRouter()
router.register(r"groups", GroupViewSet, basename="groups")
router.register(r"assignments", AssignmentViewSet, basename="assignments")

urlpatterns = [
    path("register/", RegisterView.as_view()),
    path("login/", LoginView.as_view()),
    path("refresh/", TokenRefreshView.as_view()),
    path("assignments/feed/", StudentAssignmentFeedView.as_view()),
    path("assignments/teacher/feed/", TeacherAssignmentFeedView.as_view()),
    path("student/profile/", MyStudentProfileView.as_view()),
    path("student/avatar/", MyStudentAvatarView.as_view()),
    path("teacher/profile/", MyTeacherProfileView.as_view()),
    path("teacher/avatar/", MyStudentAvatarView.as_view()),
    path("public/students/<int:pk>/", PublicStudentProfileView.as_view()),
    path("public/teachers/<int:pk>/", PublicTeacherProfileView.as_view()),
    path("invite-code/", GenerateTeacherInviteCodeView.as_view()),
    path("change-crystals/<int:student_id>/", ChangeCrystalsView.as_view()),
    path("groups/invite-code/", GroupInviteCodeView.as_view()),
    path("student/join-group/", StudentJoinGroupView.as_view()),
    path("admin/dashboard/", AdminDashboardView.as_view()),
    path("admin/invite-code/", AdminInviteCodeView.as_view()),
    path("admin/groups/<int:group_id>/lessons/", AdminGroupLessonsView.as_view(), name="admin-group-lessons"),
    path("admin/groups/<int:group_id>/lessons/<int:lesson_id>/", AdminGroupLessonDetailView.as_view(), name="admin-group-lesson-detail"),
    path("", include(router.urls)),
    path("shop/items/", ShopItemListView.as_view(), name="shop-items"),
    path("shop/buy/<int:item_id>/", BuyItemView.as_view(), name="shop-buy"),
    path("shop/my-purchases/", MyPurchasesView.as_view(), name="shop-my-purchases"),
    path("shop/my-purchases/<int:purchase_id>/activate/", ActivatePurchaseView.as_view(), name="shop-activate"),
    path("teachers/student/<int:student_id>/purchases/", TeacherStudentPurchasesView.as_view(), name="teacher-student-purchases"),
    path("lessons/", LessonViewSet.as_view({"get": "list", "post": "create"}), name="lesson-list"),
    path("lessons/<int:pk>/", LessonViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="lesson-detail"),
    path("lessons/<int:lesson_id>/attendance/", LessonAttendanceView.as_view(), name="lesson-attendance"),
    path("lessons/current/", CurrentLessonView.as_view(), name="current-lesson"),
    path("student/statistics/", StudentStatisticsView.as_view(), name="student-statistics"),
    path("student/leaderboard/", GroupLeaderboardView.as_view(), name="group-leaderboard"),
    path("student/monthly-grades/", MonthlyGradesView.as_view(), name="monthly-grades"),
    path("schedule/", ScheduleView.as_view(), name="schedule"),
    path("teacher/students/", TeacherStudentsView.as_view(), name="teacher-students"),
    path("teacher/students/<int:student_id>/assignments/", StudentAssignmentsView.as_view(), name="student-assignments"),
    path("teacher/students/<int:student_id>/assignments/<int:assignment_id>/grade/", GradeAssignmentView.as_view(), name="grade-assignment"),
    path('test-error/', views.trigger_error_view, name='test-error'),
    path("daily-quests/", DailyQuestView.as_view(), name="daily-quests"),
    path("badges/", BadgeListView.as_view(), name="badge-list"),
    path("my-badges/", MyBadgeView.as_view(), name="my-badges"),
    path("level-rewards/", LevelRewardListView.as_view(), name="level-rewards"),
    path("notifications/", NotificationListView.as_view(), name="notifications-list"),
    path("notifications/unread-count/", NotificationUnreadCountView.as_view(), name="notifications-unread-count"),
    path("notifications/mark-read/", NotificationMarkReadView.as_view(), name="notifications-mark-read"),
    path('roulette/', RouletteView.as_view(), name='roulette'),
]
